version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ruby_blog_dev
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    command: redis-server
  
  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    env_file: .env
    command: bash -c "bundle exec sidekiq"

  web:
    build: .
    ports:
      - "3000:3000"
    command: bash -c "bundle install && rails db:migrate && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    